### ISSUE TITLE
readline 시 back-slash 이슈 및 토큰화 함수 관련

### ISSUE THREAD

**Issue by hyuntall** [jiwon0829/minishell#14]
## readline 시 back-slash 이슈

> **bash**

<img width="333" alt="image" src="https://user-images.githubusercontent.com/71054445/205603338-47691331-42fe-4331-a6ca-f6d9628a76d5.png">

readline 시 back-slash를 입력할 경우, 다음 문자를 입력해야만 입력이 종료된다.

> **minishell**

<img width="408" alt="image" src="https://user-images.githubusercontent.com/71054445/205603575-7a257e79-476e-4151-95ee-0f730753b7b3.png">

back-slash를 닫아주지 않아도 입력이 종료된다.

이것도 처리해야할 듯...

## 토큰화 함수 관련

토큰화 하는 함수가 너무 길어지고 지저분해져서, 토큰화 시 공통점끼리 묶어서 4개 그룹으로 함수를 분리 시켰는데
아직도 지저분하긴 한 것 같거든 일단 이렇게라도 해보려는데 어떤지 피드백 좀 해주세요~

<img width="653" alt="image" src="https://user-images.githubusercontent.com/71054445/205604006-f67100a3-845d-4d3f-b42b-24395af1e534.png">

**Comment by jiwon0829** [comment]
- 토큰화 함수의 경우에는 이전의 상태보다는 좋은것같아요!!
- readline 시 back-slash 입력의 경우에는 프로젝트를 Mandatory part의 요구에 맞추어 구현할것인지 bash를 참고하여 구현할것인지에 대한 기준이 필요합니다...! 기준 정의 후 issues 닫겠습니다.

**Comment by jiwon0829** [comment]
[Shell Command Language](https://pubs.opengroup.org/onlinepubs/009604499/utilities/xcu_chap02.html#tag_02_02_01)
