### ISSUE TITLE
왜 하신거죠?

### ISSUE THREAD

**Issue by jiwon0829** [jiwon0829/minishell#50]
https://github.com/jiwon0829/minishell/blob/275706e5629df5280441efe08d337b8a3d204fba/src/tokenizer/process_token.c#L128-L129

**Comment by hyuntall** [comment]
일반 문자열로 해석되는 토큰들을 이어붙여주며 파싱 하는데,
토큰을 이어붙여주다가 특수토큰을 만나게 되면 이어붙여주는 과정을 멈추고 리턴하는 겁니다.
많이 지저분하지요? 이해좀 부탁드려요 저 때 심신 미약이었어요.

**Comment by jiwon0829** [comment]
필요없는 구문이면 지우겠습니다!

**Comment by hyuntall** [comment]
아마 필요한 구문이었던 것 같은데 혹시 모르니 지우고 한번 실행시켜보시겠어요?
아 그리고 토큰 종류도 더 다양해져서 11 ~ 14 뿐만 아니라 범위 증설할 필요도 있어 보입니다.

**Comment by jiwon0829** [comment]
while문 조건이 type>=1 && type <= 5일때 break이므로 해당 if문에 들어오지않을거라고 생각됩니다

**Comment by hyuntall** [comment]
어 그러네요 내가 저걸 언제 추가했지 지우셔도 될 것 같습니다.

**Comment by jiwon0829** [comment]
ㅋㅋㅋㅋㅋ네엡
