### ISSUE TITLE
line의 quote 처리 관련 이슈 및 토큰화

### ISSUE THREAD

**Issue by hyuntall** [jiwon0829/minishell#9]
# line quote 처리 관련 이슈

<img width="534" alt="image" src="https://user-images.githubusercontent.com/71054445/205492661-06e40730-d5b7-411e-b7d8-e1c2b0bfaa69.png">

<img width="422" alt="image" src="https://user-images.githubusercontent.com/71054445/205492706-72ce72c5-846d-485b-87a5-ae38b65023ba.png">

back-slash를 입력하면 quote 자체를 출력하기 때문에 정상적으로 출력이 되어야 한다...!

# line tokeize

> 기존에는 공백 및 quote을 기준으로 split하려 했으나, 복잡한 형태의 line이 주어지면, 정확하게 나눌 수 없었다.
따라서 normal, space, quote, double-quote, back-slash, dollar의 경우들마다 각각 타입을 지정해주고 링크드 리스트에 저장해주었다.
## minishell.h
<img width="340" alt="image" src="https://user-images.githubusercontent.com/71054445/205492244-104ab452-65a1-4598-8ceb-7f79d4f3ee60.png">

> 아직 확실하게 정하진 않았으나 러프한 방식으로 링크드 리스트를 구현하고, 각 노드마다 문자열, 해당 문자열의 type을 저장하였다.

## process_line.c
<img width="689" alt="image" src="https://user-images.githubusercontent.com/71054445/205492317-0edcae9c-93f4-4c1c-a6c7-92589bd3d0ce.png">

> input을 한글자씩 검사하면서, 특수한 경우가 발견되면 해당 부분만큼의 단어만 추출하여 링크드 리스트에 저장한다.

**ex) quote의 경우**
<img width="565" alt="image" src="https://user-images.githubusercontent.com/71054445/205492406-e0f8671e-9829-4f1d-90ca-56dc0275fe08.png">

> (+ 추가로 process_line 함수 타입 void로 변경)

## check_input.c
<img width="682" alt="image" src="https://user-images.githubusercontent.com/71054445/205492529-db444820-238e-47f3-ae72-28b16be4130e.png">

**handle_prompt** 함수 내에 작성
> 각 문자열과 해당 타입이 링크드 리스트에 저장이 잘 되었는지 확인하기 위해 임시로 작성해두었다.

## 출력 결과
<img width="651" alt="image" src="https://user-images.githubusercontent.com/71054445/205492978-20263331-a031-4f2f-b6c5-7aca8a8fc1cf.png">

- 아마 지금 내가 작성 중한 코드가 좀 지저분한 상태일 것 같은데, 잘 확인해보시고 문제 있으면 피드백 주세여~

**Comment by jiwon0829** [comment]
\' 출력처리와 closed quotes를 위한 readline 도중 ctrl+c 시그널 날라오면 segmentation fault뜨는 것도 해결하겠습니다!
strjoin 사용 후 free를 하지않아서 발생하는 문제같아요~
